#ifndef QTWRAPERCSIDE_GLOBAL_H
#define QTWRAPERCSIDE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTWRAPERCSIDE_LIBRARY)
#  define QTWRAPERCSIDE_EXPORT Q_DECL_EXPORT
#else
#  define QTWRAPERCSIDE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTWRAPERCSIDE_GLOBAL_H
